Datepicker fixes
conecenter/c4front pull request #24
Opened 2022-02-14 13:57 UTC by Aleafan

2022-02-18 07:04 UTC, IlyaHalsky requested changes

2022-02-18 07:04 UTC, IlyaHalsky commented on src/extra/datepicker/datepicker-actions.ts
> +    memoInputValue: React.MutableRefObject<string>,
Хмм, подозрительная штука. Кажется тут что-то не так.

2022-02-18 07:04 UTC, IlyaHalsky commented on src/extra/datepicker/datepicker-calendar.tsx
> +  const [popupMonthPos] = usePopupPos(popupMonthRef) as PopupPosition[];
Думаю есть смысл обернуть функцию Серёги тс-ом, тогда не надо будет везде писать as PP[]

2022-02-21 07:04 UTC, Aleafan commented on src/extra/datepicker/datepicker-calendar.tsx
> +  const [popupMonthPos] = usePopupPos(popupMonthRef) as PopupPosition[];
Есть 2 способа взаимодействия с js файлами в ts - 1) создавать одноименные .d.ts файлы с типами для каждого js файла; 2) использовать синтакс JSDocs для уточнения типов в комментах в js файле. Использовал JSDocs - все сразу упростилось.

2022-02-21 14:54 UTC, merged